# create a dev conda environment with: `conda env create -f environment.yml`
name: stimwalker
channels:
- conda-forge
dependencies:
- python ==3.12
- numpy
- nidaqmx-python
- pip
- pip:
  - crccheck 
  - colorama 
  - pyserial 
- pytest
- matplotlib
