name: Run server tests

on: [pull_request]

env:
  PYTHONPATH: ./server/external/pyScienceMode

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            prefix: /usr/share/miniconda3/envs/stimwalker
          - os: macos-latest
            label: Macos
            prefix: /Users/runner/miniconda3/envs/stimwalker
          - os: windows-latest
            label: Windows
            prefix: C:\Miniconda3\envs\stimwalker
    name: Tests on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: stimwalker
          environment-file: server/environment.yml

      - name: Print mamba info
        run: |
          mamba config --show
          mamba info
          mamba list

      - name: Install extra dependencies
        run: | 
          mamba install black pytest pytest-cov codecov packaging -cconda-forge


      - name: Run tests without coverage
        run: pytest -v --color=yes server/tests
        if: matrix.label != 'Linux'

      - name: Run tests with coverage
        run: |
          pytest -v --color=yes --cov-report term-missing --cov=stimwalker server/tests
          codecov
        if: matrix.label == 'Linux'
